// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gomoku_impl.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PieceType int32

const (
	PieceType_NONE  PieceType = 0
	PieceType_BLANK PieceType = 1
	PieceType_WHITE PieceType = 2
)

var PieceType_name = map[int32]string{
	0: "NONE",
	1: "BLANK",
	2: "WHITE",
}

var PieceType_value = map[string]int32{
	"NONE":  0,
	"BLANK": 1,
	"WHITE": 2,
}

func (x PieceType) Enum() *PieceType {
	p := new(PieceType)
	*p = x
	return p
}

func (x PieceType) String() string {
	return proto.EnumName(PieceType_name, int32(x))
}

func (x *PieceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PieceType_value, data, "PieceType")
	if err != nil {
		return err
	}
	*x = PieceType(value)
	return nil
}

func (PieceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28ebe3e1361c329b, []int{0}
}

type Position struct {
	X                    *int32   `protobuf:"varint,1,req,name=x" json:"x,omitempty"`
	Y                    *int32   `protobuf:"varint,2,req,name=y" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_28ebe3e1361c329b, []int{0}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Position) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type PiecePosition struct {
	Type                 *PieceType `protobuf:"varint,1,req,name=type,enum=proto.PieceType" json:"type,omitempty"`
	Position             *Position  `protobuf:"bytes,2,req,name=position" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PiecePosition) Reset()         { *m = PiecePosition{} }
func (m *PiecePosition) String() string { return proto.CompactTextString(m) }
func (*PiecePosition) ProtoMessage()    {}
func (*PiecePosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_28ebe3e1361c329b, []int{1}
}

func (m *PiecePosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PiecePosition.Unmarshal(m, b)
}
func (m *PiecePosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PiecePosition.Marshal(b, m, deterministic)
}
func (m *PiecePosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PiecePosition.Merge(m, src)
}
func (m *PiecePosition) XXX_Size() int {
	return xxx_messageInfo_PiecePosition.Size(m)
}
func (m *PiecePosition) XXX_DiscardUnknown() {
	xxx_messageInfo_PiecePosition.DiscardUnknown(m)
}

var xxx_messageInfo_PiecePosition proto.InternalMessageInfo

func (m *PiecePosition) GetType() PieceType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return PieceType_NONE
}

func (m *PiecePosition) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type Board struct {
	ChessPositions       []*PiecePosition `protobuf:"bytes,1,rep,name=chessPositions" json:"chessPositions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Board) Reset()         { *m = Board{} }
func (m *Board) String() string { return proto.CompactTextString(m) }
func (*Board) ProtoMessage()    {}
func (*Board) Descriptor() ([]byte, []int) {
	return fileDescriptor_28ebe3e1361c329b, []int{2}
}

func (m *Board) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Board.Unmarshal(m, b)
}
func (m *Board) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Board.Marshal(b, m, deterministic)
}
func (m *Board) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Board.Merge(m, src)
}
func (m *Board) XXX_Size() int {
	return xxx_messageInfo_Board.Size(m)
}
func (m *Board) XXX_DiscardUnknown() {
	xxx_messageInfo_Board.DiscardUnknown(m)
}

var xxx_messageInfo_Board proto.InternalMessageInfo

func (m *Board) GetChessPositions() []*PiecePosition {
	if m != nil {
		return m.ChessPositions
	}
	return nil
}

type IsFirst struct {
	IsFirst              *bool    `protobuf:"varint,1,req,name=isFirst" json:"isFirst,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsFirst) Reset()         { *m = IsFirst{} }
func (m *IsFirst) String() string { return proto.CompactTextString(m) }
func (*IsFirst) ProtoMessage()    {}
func (*IsFirst) Descriptor() ([]byte, []int) {
	return fileDescriptor_28ebe3e1361c329b, []int{3}
}

func (m *IsFirst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsFirst.Unmarshal(m, b)
}
func (m *IsFirst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsFirst.Marshal(b, m, deterministic)
}
func (m *IsFirst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsFirst.Merge(m, src)
}
func (m *IsFirst) XXX_Size() int {
	return xxx_messageInfo_IsFirst.Size(m)
}
func (m *IsFirst) XXX_DiscardUnknown() {
	xxx_messageInfo_IsFirst.DiscardUnknown(m)
}

var xxx_messageInfo_IsFirst proto.InternalMessageInfo

func (m *IsFirst) GetIsFirst() bool {
	if m != nil && m.IsFirst != nil {
		return *m.IsFirst
	}
	return false
}

type Status struct {
	Status               *bool    `protobuf:"varint,1,req,name=status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_28ebe3e1361c329b, []int{4}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetStatus() bool {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return false
}

func init() {
	proto.RegisterEnum("proto.PieceType", PieceType_name, PieceType_value)
	proto.RegisterType((*Position)(nil), "proto.Position")
	proto.RegisterType((*PiecePosition)(nil), "proto.PiecePosition")
	proto.RegisterType((*Board)(nil), "proto.Board")
	proto.RegisterType((*IsFirst)(nil), "proto.IsFirst")
	proto.RegisterType((*Status)(nil), "proto.Status")
}

func init() { proto.RegisterFile("gomoku_impl.proto", fileDescriptor_28ebe3e1361c329b) }

var fileDescriptor_28ebe3e1361c329b = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4b, 0xf3, 0x40,
	0x10, 0xc5, 0x9b, 0x7e, 0x4d, 0x9b, 0x4c, 0xdb, 0x7c, 0x71, 0x10, 0x09, 0x3d, 0x85, 0x55, 0xb4,
	0x58, 0x28, 0x98, 0xb3, 0x17, 0x0b, 0x11, 0x83, 0x1a, 0x4b, 0x5a, 0xf0, 0x28, 0x31, 0x2e, 0xba,
	0xd4, 0x66, 0x43, 0x76, 0x2b, 0xcd, 0x7f, 0x2f, 0xdd, 0x6c, 0x82, 0x88, 0xa7, 0xcc, 0xcb, 0xfc,
	0xe6, 0xcd, 0x9b, 0x85, 0xa3, 0x77, 0xbe, 0xe5, 0x9b, 0xdd, 0x0b, 0xdb, 0x16, 0x9f, 0xf3, 0xa2,
	0xe4, 0x92, 0xa3, 0xa9, 0x3e, 0xe4, 0x1c, 0xac, 0x25, 0x17, 0x4c, 0x32, 0x9e, 0xe3, 0x08, 0x8c,
	0xbd, 0x67, 0xf8, 0xdd, 0xa9, 0x99, 0x18, 0xfb, 0x83, 0xaa, 0xbc, 0x6e, 0xad, 0x2a, 0xf2, 0x0a,
	0xe3, 0x25, 0xa3, 0x19, 0x6d, 0xe1, 0x33, 0xe8, 0xc9, 0xaa, 0xa0, 0x8a, 0x77, 0x02, 0xb7, 0x76,
	0x9d, 0x2b, 0x66, 0x5d, 0x15, 0x34, 0x51, 0x5d, 0x9c, 0x81, 0x55, 0xe8, 0x09, 0xe5, 0x35, 0x0c,
	0xfe, 0x37, 0xa4, 0xfe, 0x9d, 0xb4, 0x00, 0x09, 0xc1, 0x5c, 0xf0, 0xb4, 0x7c, 0xc3, 0x6b, 0x70,
	0xb2, 0x0f, 0x2a, 0x44, 0xc3, 0x08, 0xcf, 0xf0, 0xff, 0x4d, 0x87, 0xc1, 0xf1, 0xcf, 0x2d, 0xad,
	0xc1, 0x2f, 0x96, 0x9c, 0xc2, 0x20, 0x12, 0xb7, 0xac, 0x14, 0x12, 0x3d, 0x18, 0xb0, 0xba, 0x54,
	0x39, 0xad, 0xa4, 0x91, 0xc4, 0x87, 0xfe, 0x4a, 0xa6, 0x72, 0x27, 0xf0, 0x04, 0xfa, 0x42, 0x55,
	0x1a, 0xd1, 0xea, 0x72, 0x06, 0x76, 0x7b, 0x0d, 0x5a, 0xd0, 0x8b, 0x9f, 0xe2, 0xd0, 0xed, 0xa0,
	0x0d, 0xe6, 0xe2, 0xe1, 0x26, 0xbe, 0x77, 0x8d, 0x43, 0xf9, 0x7c, 0x17, 0xad, 0x43, 0xb7, 0x1b,
	0xe4, 0xe0, 0x3e, 0xa6, 0x1b, 0xaa, 0x06, 0x56, 0xb4, 0xfc, 0x62, 0x19, 0xc5, 0x0b, 0xe8, 0x45,
	0x39, 0x93, 0xe8, 0xe8, 0xd4, 0x3a, 0xd4, 0x64, 0xac, 0x75, 0xbd, 0x9f, 0x74, 0xf0, 0x0a, 0xec,
	0x76, 0x18, 0x47, 0xba, 0xab, 0x5e, 0x62, 0xf2, 0xe7, 0xc5, 0xa4, 0xf3, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0xaa, 0x5e, 0x9a, 0xfc, 0xd1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MakePieceServiceClient is the client API for MakePieceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MakePieceServiceClient interface {
	Init(ctx context.Context, in *IsFirst, opts ...grpc.CallOption) (*Status, error)
	MakePiece(ctx context.Context, in *Board, opts ...grpc.CallOption) (*PiecePosition, error)
}

type makePieceServiceClient struct {
	cc *grpc.ClientConn
}

func NewMakePieceServiceClient(cc *grpc.ClientConn) MakePieceServiceClient {
	return &makePieceServiceClient{cc}
}

func (c *makePieceServiceClient) Init(ctx context.Context, in *IsFirst, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/proto.MakePieceService/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *makePieceServiceClient) MakePiece(ctx context.Context, in *Board, opts ...grpc.CallOption) (*PiecePosition, error) {
	out := new(PiecePosition)
	err := c.cc.Invoke(ctx, "/proto.MakePieceService/MakePiece", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MakePieceServiceServer is the server API for MakePieceService service.
type MakePieceServiceServer interface {
	Init(context.Context, *IsFirst) (*Status, error)
	MakePiece(context.Context, *Board) (*PiecePosition, error)
}

// UnimplementedMakePieceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMakePieceServiceServer struct {
}

func (*UnimplementedMakePieceServiceServer) Init(ctx context.Context, req *IsFirst) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedMakePieceServiceServer) MakePiece(ctx context.Context, req *Board) (*PiecePosition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakePiece not implemented")
}

func RegisterMakePieceServiceServer(s *grpc.Server, srv MakePieceServiceServer) {
	s.RegisterService(&_MakePieceService_serviceDesc, srv)
}

func _MakePieceService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFirst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakePieceServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MakePieceService/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakePieceServiceServer).Init(ctx, req.(*IsFirst))
	}
	return interceptor(ctx, in, info, handler)
}

func _MakePieceService_MakePiece_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Board)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakePieceServiceServer).MakePiece(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MakePieceService/MakePiece",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakePieceServiceServer).MakePiece(ctx, req.(*Board))
	}
	return interceptor(ctx, in, info, handler)
}

var _MakePieceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MakePieceService",
	HandlerType: (*MakePieceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _MakePieceService_Init_Handler,
		},
		{
			MethodName: "MakePiece",
			Handler:    _MakePieceService_MakePiece_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gomoku_impl.proto",
}
